apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  labels:
    app: bff
    {{- include "target.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.bff.replicaCount }}
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: "{{ .Values.bff.image.repository }}:{{ .Values.bff.image.tag }}"
          imagePullPolicy: {{ .Values.bff.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.bff.service.port }}
